### ISSUE TITLE
KeyError: 'mac'

### ISSUE THREAD

**Issue by elipothier** [google/python-laurel#12]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eli/.local/share/Trash/files/python-laurel/laurel/__init__.py", line 101, in __init__
    mac = [bulb['mac'][i:i+2] for i in range(0, 12, 2)]
  File "/home/eli/.local/share/Trash/files/python-laurel/laurel/__init__.py", line 101, in <listcomp>
    mac = [bulb['mac'][i:i+2] for i in range(0, 12, 2)]
KeyError: 'mac'

**Comment by altodd** [comment]
I've run into the same problem, Printing the bulb object looks like there is no mac... Let me know if you figure anything out. I'm trying to make it work as well.

**Comment by mjg59** [comment]
Could you modify get_properties() to have:
```
print(r.text)
```
just before the
```
return r.json()
```

include an example that's missing a mac entry? What sort of device is this?

**Comment by altodd** [comment]
I actually can’t do that very easily. I needed something that worked, so
after about a day threw out the c by ge toggle switches I had and used some
Kasa hs200’s instead and those have been working great since then, but
since they’re wall switches I don’t have an easy way to plug them back in
and try anything. From what it looked like to me, the data was there but in
a different part of the JSON object than where the code was looking. Since
I had thrown a whole day into it and didn’t know how much longer it would
take I just abandoned it. I had set up burp suite between the c by ge app
and inspected the JSON to verify the Mac issue. I unfortunately was just
trying to get things working and didn’t think to save that, but if there’s
enough interest I could see about hooking the switches up to a power supply
and giving some data here.

**Comment by mjg59** [comment]
If you still have the GE account then you should be able to get that data without the switches being hooked up at all, but no worries if you're not - I understand just moving on to solve the problem! Was your toggle switch one of these: https://www.amazon.com/GE-Lighting-93105376-Single-Pole-Replacement/dp/B07NWB7S86 ? I don't have any of the wifi devices so they may well be incompatible. I'll look into that.

**Comment by altodd** [comment]
Yes, it was those light switches. I had bought them because of their WiFi
capability but realized this code was using Bluetooth so I had tried both
this code and trying to add some of my own requests to the api (by trying
to reverse their api/app for the web requests before deciding that was too
much trouble, and maybe their api is just for info, I didn’t get that far
into their app although I did notice there was another api url that this
code doesn’t call). I will go back and try adding that, as I believe I
still have the account. That’s on a raspberry pi at my church though so
I’ll have to set things up on another device and pull the dependencies or
access that pi, either way it will be a few days but I can go back and run
that print statement. I’ll add it to my to-do list.
