### ISSUE TITLE
Laurel object is not subscriptable

### ISSUE THREAD

**Issue by JAbelP** [google/python-laurel#3]
the code I have on my Rasberry pi 3
I am running it on python3 as bluepy would not install on python 2.7

import laurel

devices = laurel.laurel("myUserName","myPassword")

devices[0].set_power(False)

The error I get is 
Traceback (most recent call last):
    File"<where my file is>
        devices[0]/set_power(False)
TyoeError: 'laurel' object is not subscriptable

**Comment by jcconnell** [comment]
Try `devices.devices[0].name`.

**Comment by shannb2012** [comment]
I keep getting this error when I execute


>>> devices = laurel.laurel("username", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/__init__.py", line 100, in __init__
    id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable
>>> devices = laurel.laurel("shannb2012@gmail.com", "shannon2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/__init__.py", line 100, in __init__
    id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable
>>> devices = laurel.laurel("shannb2012@gmail.com", "shannon2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/__init__.py", line 100, in __init__
    id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable

**Comment by shannb2012** [comment]
I keep getting this error on MacOS Catalina 

devices = laurel.laurel("username", "password")
Traceback (most recent call last):
File "", line 1, in
File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/init.py", line 100, in init
id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable
devices = laurel.laurel("username", "password")
Traceback (most recent call last):
File "", line 1, in
File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/init.py", line 100, in init
id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable
devices = laurel.laurel("username", "password")
Traceback (most recent call last):
File "", line 1, in
File "/Users/shannonbrown/Desktop/lights/python-laurel/laurel/init.py", line 100, in init
id = int(bulb['deviceID'][-3:])
TypeError: 'int' object is not subscriptable

**Comment by tleibert** [comment]
I went in and changed this line in the `laurel.__init__` from `id = int(bulb['deviceID'])[-3:])` to `id = int(bulb['deviceID'])` and it resolved the error. I dug some more and it seems that `bulb['deviceID')` is already an int, explaining why you can't subscript it.
